services:
  php:
    build: ./docker/php
    volumes:
      - ./docker/php/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./application:/var/www/html
    ports:
      - ${PHP_PORT}:80

  mysql:
    image: mysql:8.4
    volumes:
      - ./docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/mysql/entrypoint:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    ports:
      - ${PMA_PORT}:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - ${MH_SMTP_PORT}:1025
      - ${MH_WEBUI_PORT}:8025
